common:
    seed: &seed 2020
    target: target
    drop:
    kaggle:
        submit: False

model:
    name: efficientnet_b3
    n_channels: &channel 3
    n_classes: 1
    pretrained: True
    multi_gpu: True
    avgpool:
        name: GeM
        params: {}
    head:
        act:
            name: ReLU
            params: {}
        batch_norm: 
            name: BatchNorm1d
            params:
                num_features: 1536
        drop:
            name: Dropout
            params:
                p: 0.3
        linear:
            name: Linear
            params:
                in_features: 1536
                out_features: 128
    metric:

validation:
    name: SingleFold
    params:
        n_splits: 5
        shuffle: True
        random_state: *seed
    split:
        y: target
        groups:
    weight:
        - 1.0

data:
    train:
        dataset_type: CustomDataset
        is_train: True
        img_size:
            width: &wsize 384
            height: &hsize 384
        n_channels: *channel
        epochs: 10
        loader:
            shuffle: True
            batch_size: 32
            num_workers: 4
        transforms:
            hflip:
                name: HorizontalFlip
                params:
                    p: 0.5
            vflip:
                name: VerticalFlip
                params:
                    p: 0.5
    valid:
        dataset_type: CustomDataset
        is_train: True
        img_size:
            width: *wsize
            height: *hsize
        n_channels: *channel
        loader:
            shuffle: False
            batch_size: 16
            num_workers: 4
        transforms:
        tta:
            iter_num: 1
    test:
        dataset_type: CustomDataset
        is_train: False
        img_size:
            width: *wsize
            height: *hsize
        n_channels: *channel
        loader:
            shuffle: False
            batch_size: 16
            num_workers: 4
        transforms:
        tta:
            iter_num: 1

loss: 
    name: BCEWithLogitsLoss
    params: {}

optimizer:
    name: Adam
    params:
        lr: 0.001

scheduler:
    name: ReduceLROnPlateau
    params:
        factor: 0.5
        T_max: 3