common:
    seed: &seed 2020
    target: target
    metrics:
        name: auc
        params: {}
    drop:
    kaggle:
        submit: True


data:
    sample:
        name: sample_submission
    drop:
        name:
    option:
        rank_avg: True
    models:
        model1:
            name: efficientnetb3_037_20200803002502_0.920
        model2:
            name: se_resnext50_32x4d_004_20200803235954_0.920
