common:
    seed: &seed 2020
    drop:
    metrics:
        name: auc
        params: {}
    kaggle:
        submit: False

data:
    loader:
        train:
            data_type: train
            reduce: False
        test:
            data_type: test
            reduce: False
    features:
        name: custom_001
        cat_features:
        oof:
            name:
    target:
        name: target
        convert_type:
        reconvert_type:
    adversarial_validation: False

validation:
    name: StratifiedGroupKFold
    params:
        n_splits: 5
    split:
        y: target
        groups: patient_id
    weight:
        - 0.2
    single: True

model:
    name: lightgbm
    task_type: classification
    params:
        boosting_type: gbdt
        objective: binary
        metric: auc
        learning_rate: 0.01
        num_leaves: 32
        min_child_samples: 20
        feature_fraction: 0.8
        bagging_fraction: 0.8
        bagging_freq: 1
        bagging_seed: 11
        max_bin: 255
        verbose: -1
        nthread: -1
        seed: *seed
        first_metric_only: True
    num_boost_round: 10000
    verbose_eval: 200
    early_stopping_rounds: 200
    imp_type: gain