common:
    seed: &seed 2020
    target: target
    metrics:
        name: auc
        params: {}
    drop:
    kaggle:
        submit: False

model:
    name: resnet18
    n_channels: &channel 3
    n_classes: 1
    pretrained: True
    multi_gpu: True
    avgpool:
        name: GeM
        params: {}
    head:
        act:
            name: ReLU
            params: {}
        drop:
            name: Dropout
            params:
                p: 0.3
        linear:
            name: Linear
            params:
                in_features: 512
                out_features: 256
        act:
            name: ReLU
            params: {}
        drop:
            name: Dropout
            params:
                p: 0.3
        linear:
            name: Linear
            params:
                in_features: 256
                out_features: 1
    metric:

validation:
    val1:
        name: StratifiedGroupKFold
        params:
            n_splits: 5
        split:
            y: target
            groups: patient_id
        weight:
            - 0.2
        single: False
    val2:
        name: StratifiedKFold
        params:
            n_splits: 5
            random_state: *seed
        split:
            y: target
            groups:
        weight:
            - 0.2
        single: False

data:
    train:
        dataset_type: CustomDataset
        is_train: True
        img_size:
            width: &wsize 384
            height: &hsize 384
        n_channels: *channel
        epochs: 3
        loader:
            shuffle: True
            batch_size: 128
            num_workers: 4
        transforms:
            hflip:
                name: HorizontalFlip
                params:
                    p: 0.5
            vflip:
                name: VerticalFlip
                params:
                    p: 0.5
            rotate:
                name: Rotate
                params:
                    p: 0.5
                    limit: 20
            cutout:
                name: Cutout
                params:
                    p: 0.5
                    num_holes: 30
                    max_h_size: 15
                    max_w_size: 15
        mixup: False
    valid:
        dataset_type: CustomDataset
        is_train: True
        img_size:
            width: *wsize
            height: *hsize
        n_channels: *channel
        loader:
            shuffle: False
            batch_size: 32
            num_workers: 4
        transforms:
        tta:
            iter_num: 1
    test:
        dataset_type: CustomDataset
        is_train: False
        img_size:
            width: *wsize
            height: *hsize
        n_channels: *channel
        loader:
            shuffle: False
            batch_size: 32
            num_workers: 4
        transforms:
        tta:
            iter_num: 1

loss: 
    name: WeightedFocalLoss
    params:
        alpha: 0.25
        gamma: 2

optimizer:
    name: Adam
    params:
        lr: 0.0001

scheduler:
    name: CosineAnnealingLR
    params:
        eta_min: 0.000001
        T_max: 10