common:
    seed: &seed 2020
    target: target
    metrics:
        name: auc
        params: {}
    drop:
    kaggle:
        submit: True

model:
    name: resnest50
    n_channels: &channel 3
    n_classes: 1
    pretrained: False
    multi_gpu: True
    avgpool:
        name: GeM
        params: {}
    head:
        act:
            name: ReLU
            params: {}
        drop:
            name: Dropout
            params:
                p: 0.3
        linear:
            name: Linear
            params:
                in_features: 2048
                out_features: 1
    metric:

validation:
    val1:
        name: StratifiedGroupKFold
        params:
            n_splits: 5
        split:
            y: target
            groups: patient_id
        weight:
            - 0.2
        single: False
    val2:
        name: StratifiedKFold
        params:
            n_splits: 5
            random_state: *seed
        split:
            y: target
            groups:
        weight:
            - 0.2
        single: False

data:
    train:
        dataset_type: CustomDataset
        is_train: True
        img_size:
            width: &wsize 384
            height: &hsize 384
        n_channels: *channel
        epochs: 10
        loader:
            shuffle: True
            batch_size: 16
            num_workers: 4
        transforms:
            hflip:
                name: HorizontalFlip
                params:
                    p: 0.5
            vflip:
                name: VerticalFlip
                params:
                    p: 0.5
            rotate:
                name: Rotate
                params:
                    p: 0.5
                    limit: 20
            augmix:
                name: RandomAugMix
                params:
                    p: 0.5
            coarse:
                name: CoarseDropout
                params:
                    p: 0.5
                    max_holes: 8
                    min_holes: 3
                    max_height: 20
                    max_width: 20
            hair:
                name: HairAugmentation
                params:
                    p: 0.5
                    max_hairs: 10

        mixup: False
    valid:
        dataset_type: CustomDataset
        is_train: True
        img_size:
            width: *wsize
            height: *hsize
        n_channels: *channel
        loader:
            shuffle: False
            batch_size: 16
            num_workers: 4
        transforms:
            hflip:
                name: HorizontalFlip
                params:
                    p: 0.5
            vflip:
                name: VerticalFlip
                params:
                    p: 0.5
            rotate:
                name: Rotate
                params:
                    p: 0.5
                    limit: 20
            augmix:
                name: RandomAugMix
                params:
                    p: 0.5
            hair:
                name: HairAugmentation
                params:
                    p: 0.5
                    max_hairs: 10
        tta:
            iter_num: 10
    test:
        dataset_type: CustomDataset
        is_train: False
        img_size:
            width: *wsize
            height: *hsize
        n_channels: *channel
        loader:
            shuffle: False
            batch_size: 16
            num_workers: 4
        transforms:
            hflip:
                name: HorizontalFlip
                params:
                    p: 0.5
            vflip:
                name: VerticalFlip
                params:
                    p: 0.5
            rotate:
                name: Rotate
                params:
                    p: 0.5
                    limit: 20
            augmix:
                name: RandomAugMix
                params:
                    p: 0.5
            hair:
                name: HairAugmentation
                params:
                    p: 0.5
                    max_hairs: 10
        tta:
            iter_num: 10

loss: 
    name: WeightedFocalLoss
    params:
        alpha: 0.25
        gamma: 2

optimizer:
    name: Adam
    params:
        lr: 0.0001

scheduler:
    name: CosineAnnealingLR
    params:
        eta_min: 0.000001
        T_max: 10